export const SUMMONS = [
  "Goon o'clock. You know the drill.",
  "The app has spoken. Go handle it.",
  "Duty calls. Literally.",
  "Time for your scheduled session.",
  "Don't skip today. The streak matters.",
  "GG. It's that time.",
  "Your daily mission has been assigned.",
  "This is not a drill. Go.",
  "The algorithm has selected you. For this.",
  "Clock's ticking. You know what to do.",
  "Wellness check. Go be well.",
  "You installed this app for a reason.",
  "Peak performance window detected.",
  "Your body is a temple. Tend to it.",
  "Reminder: you have unfinished business.",
  "The call has come from inside the phone.",
  "No excuses. No delays. Go.",
  "Another day, another session. Get to it.",
  "GG reminds you: it's been a while.",
  "Optimal conditions. Favorable window. You know.",
  "This message will self-destruct. Go first.",
  "Consider this your formal summons.",
  "The council has convened. Decision: go.",
  "Scheduled maintenance time.",
  "You've been selected. Participation is encouraged.",
  "Daily objectives updated. Primary: you know.",
  "Conditions are favorable. Begin when ready.",
  "Status check: pending. Resolve it.",
  "Your presence is requested. Immediately.",
  "GG has determined you are due. Go.",
];

export const HEALTH_TIPS = [
  "Studies suggest 3-5x weekly is optimal. You're on the right track.",
  "Regular sessions support prostate health. Science agrees with your lifestyle.",
  "Stress cortisol drops significantly post-session. You're basically meditating.",
  "Dopamine regulation improves with consistent healthy habits. Keep it up.",
  "Sleep quality correlates with regular release cycles. You're a genius.",
  "Immune function gets a mild boost. You're practically taking vitamins.",
  "Blood pressure reduction is a documented benefit. Heart health, baby.",
  "Mental clarity often follows. You're optimizing your brain.",
  "Endorphin release is equivalent to a light jog. Except way better.",
  "Healthy frequency varies by individual. Honor your body's rhythm.",
  "Pelvic floor health is improved by regular engagement. Functional fitness.",
  "Oxytocin release supports emotional regulation. You're emotionally intelligent.",
  "Skin health may improve due to hormonal balance. You're glowing.",
  "Creativity often spikes post-session. Artists know this.",
  "Pain tolerance temporarily increases. You're basically an athlete.",
  "Concentration tends to improve afterward. Peak performance protocol.",
  "Testosterone regulation benefits from consistent healthy habits.",
  "Anxiety reduction is a documented short-term effect. Cheaper than therapy.",
  "Muscle tension releases. It's basically a massage.",
  "Your circadian rhythm appreciates consistent biological signals.",
];
